chore: migrate api routes from pages to app
annuaire-entreprises-data-gouv-fr/site pull request #1266
Opened 2024-10-11 10:18 UTC by rmonnier9

- Migration
- Zones impactées : `api/auth/agent-connect`, `api/auth/france-connect` et `api/download/espace-agent/documents/[slug]/route.ts`.
- Détails :
  - Migration sur App Router

2024-10-14 12:39 UTC, XavierJp commented
Could not make it work, both AgentConnect and FranceConnect does not work in local. FranceConnect might be unrelated to your changes though

2024-10-14 14:35 UTC, rmonnier9 commented
> Could not make it work, both AgentConnect and FranceConnect does not work in local. FranceConnect might be unrelated to your changes though

I fixed it.

When using NextResponse.redirect, full url must be used.
There is a builtin function in nextjs that allows us to use path (redirect from next/navigation) but it throws errors in its normal behavior (to stop rendering a server component for example). This behaviour messes up with our try catch.
I created an utils redirectTo that creates the url.

<img width="660" alt="image" src="https://github.com/user-attachments/assets/3cb54948-157b-484e-bad0-1fea8eb29950">

2024-10-15 07:44 UTC, XavierJp requested changes

2024-10-15 07:44 UTC, XavierJp commented on app/api/auth/utils.ts
I think this should be moved in `/utils/server-side-helper/app/redirect-to.ts`

2024-10-15 12:26 UTC, merged