fix: link to bodacc
annuaire-entreprises-data-gouv-fr/site pull request #1284
Opened 2024-10-18 13:10 UTC by rmonnier9

- Correction d'un bug.
- Détails :
  - Fix du lien

Closes #86

2024-10-21 12:13 UTC, XavierJp requested changes

2024-10-21 12:13 UTC, XavierJp commented on app/(header-default)/annonces/[slug]/_components/bodacc.tsx
> +                  )}
Would prefer an url without the replace when possible

2024-10-22 05:39 UTC, XavierJp reviewed
Sounds good to me. Only tiny issue I see is that you mutate route.ts signature. Now it can either be a function or a string. Why not only have string ?

2024-10-22 05:40 UTC, XavierJp approved these changes

2024-10-22 07:56 UTC, rmonnier9 commented
> Sounds good to me. Only tiny issue I see is that you mutate route.ts signature. Now it can either be a function or a string. Why not only have string ?

If we want to keep only strings in routes.ts, I don’t see another way than using placeholders and replacing them with .replace(). We could create a utility function to handle this for us, but it might make it less transparent what’s happening under the hood.

2024-10-22 07:57 UTC, rmonnier9 commented
I'm actually ok with both options

2024-10-22 09:57 UTC, XavierJp commented
I like your current solution

2024-10-22 09:57 UTC, merged